/** A single file's slice of a unified diff, plus the path used for exclusion/grouping. */
interface DiffFile {
  path: string;
  text: string;
}

const FILE_HEADER = /^diff --git a\/(.*) b\/(.*)$/;
const HUNK_HEADER = /^@@ .* @@/;
/** Hunk header range, capturing the new-file start line and (optional) count. */
const HUNK_RANGE = /^@@ -\d+(?:,\d+)? \+(\d+)(?:,(\d+))? @@/;

/**
 * Split a `git diff` unified-diff string into one entry per changed file,
 * preserving each file's `diff --git` header so every piece remains a valid,
 * self-describing diff on its own.
 */
function splitDiffByFile(diff: string): DiffFile[] {
  const trimmed = diff.trim();
  if (!trimmed) return [];

  const files: DiffFile[] = [];
  let path = "";
  let lines: string[] = [];

  const flush = () => {
    if (lines.length) files.push({ path, text: lines.join("\n") });
  };

  for (const line of trimmed.split("\n")) {
    const header = FILE_HEADER.exec(line);
    if (header) {
      flush();
      // Prefer the post-change path; deletions report it as `/dev/null`, so fall back to the pre-change path.
      path = header[2] !== "dev/null" ? header[2] : header[1];
      lines = [line];
    } else {
      lines.push(line);
    }
  }
  flush();

  return files;
}

/**
 * Paths excluded from review: machine-generated dependency lockfiles and
 * Yarn Plug'n'Play "zero-install" artifacts. Both are enormous, regenerated by
 * tooling rather than authored, and not meaningful to review line-by-line —
 * including them risks blowing the model's context window on their own.
 */
const EXCLUDED_PATH_PATTERNS: readonly RegExp[] = [
  /(^|\/)yarn\.lock$/,
  /(^|\/)package-lock\.json$/,
  /(^|\/)npm-shrinkwrap\.json$/,
  /(^|\/)pnpm-lock\.yaml$/,
  /(^|\/)composer\.lock$/,
  /(^|\/)Gemfile\.lock$/,
  /(^|\/)Cargo\.lock$/,
  /(^|\/)poetry\.lock$/,
  /(^|\/)Pipfile\.lock$/,
  /(^|\/)go\.sum$/,
  /(^|\/)mix\.lock$/,
  /(^|\/)flake\.lock$/,
  /(^|\/)Podfile\.lock$/,
  /(^|\/)packages\.lock\.json$/,
  /(^|\/)pubspec\.lock$/,
  /(^|\/)\.pnp\.cjs$/,
  /(^|\/)\.pnp\.loader\.mjs$/,
  /(^|\/)\.pnp\.data\.json$/,
  /^\.yarn\/cache\//,
  /^\.yarn\/unplugged\//,
  /^\.yarn\/install-state\.gz$/,
];

/** Partition `files` into those to review and the paths of those excluded. */
function partitionExcluded(files: readonly DiffFile[]): {
  kept: DiffFile[];
  excludedPaths: string[];
} {
  const kept: DiffFile[] = [];
  const excludedPaths: string[] = [];
  for (const file of files) {
    if (file.path && EXCLUDED_PATH_PATTERNS.some((pattern) => pattern.test(file.path))) {
      excludedPaths.push(file.path);
    } else {
      kept.push(file);
    }
  }
  return { kept, excludedPaths };
}

/**
 * Conservative chars-per-token estimate for diff text. Diffs skew denser than
 * prose (short identifiers, punctuation, hex hashes), so this under-counts
 * chars-per-token on purpose — better to chunk a little early than to trip the
 * model's hard context limit.
 */
const CHARS_PER_TOKEN_ESTIMATE = 3;

function estimateTokens(text: string): number {
  return Math.ceil(text.length / CHARS_PER_TOKEN_ESTIMATE);
}

/**
 * Split a single oversized file's diff into hunk-aligned pieces no larger than
 * `maxChars`, each prefixed with the file's header lines so it remains a
 * valid, self-describing diff.
 */
function splitFileByHunks(file: DiffFile, maxChars: number): DiffFile[] {
  const lines = file.text.split("\n");
  const firstHunk = lines.findIndex((line) => HUNK_HEADER.test(line));
  if (firstHunk === -1) return [file]; // nothing to split on (e.g. a binary-file notice)

  const header = lines.slice(0, firstHunk).join("\n");
  const hunks: string[] = [];
  let hunk: string[] = [];
  for (const line of lines.slice(firstHunk)) {
    if (HUNK_HEADER.test(line) && hunk.length) {
      hunks.push(hunk.join("\n"));
      hunk = [];
    }
    hunk.push(line);
  }
  if (hunk.length) hunks.push(hunk.join("\n"));

  const groups: string[][] = [[]];
  let chars = header.length;
  for (const hunkText of hunks) {
    const group = groups[groups.length - 1];
    if (group.length && chars + hunkText.length > maxChars) {
      groups.push([]);
      chars = header.length;
    }
    groups[groups.length - 1].push(hunkText);
    chars += hunkText.length;
  }

  return groups.map((group) => ({ path: file.path, text: [header, ...group].join("\n") }));
}

/**
 * Group files into chunks whose combined diff text stays within `maxChars`,
 * keeping each file's diff intact and grouped with its neighbours (in diff
 * order) wherever possible. A single file whose own diff exceeds the budget is
 * split further along hunk boundaries so no chunk overflows.
 */
function chunkDiffFiles(files: readonly DiffFile[], maxChars: number): DiffFile[][] {
  const chunks: DiffFile[][] = [];
  let current: DiffFile[] = [];
  let currentChars = 0;

  const flush = () => {
    if (current.length) chunks.push(current);
    current = [];
    currentChars = 0;
  };

  for (const file of files) {
    if (file.text.length > maxChars) {
      flush();
      for (const piece of splitFileByHunks(file, maxChars)) chunks.push([piece]);
      continue;
    }
    if (current.length && currentChars + file.text.length > maxChars) flush();
    current.push(file);
    currentChars += file.text.length;
  }
  flush();

  return chunks;
}

/**
 * Prefix every line of a unified diff with its line number in the new file,
 * so the reviewer can cite accurate `file:line` coordinates (and the publisher
 * can anchor inline comments) by reading the gutter directly instead of
 * counting lines from each hunk header — counting it almost always gets wrong.
 *
 * Hunk headers (`@@ -a +b @@`) seed the new-file counter; added (`+`) and
 * context (` `) lines carry and advance it. Removed (`-`) lines have no
 * new-file line, file headers (`diff --git`, `index`, `---`, `+++`), and the
 * `\ No newline` marker get a blank gutter. The gutter is right-aligned to the
 * widest line number in the diff so the columns line up.
 */
function annotateDiffWithLineNumbers(diff: string): string {
  const lines = diff.split("\n");

  // First pass: size the gutter to the largest new-file line number present.
  let maxLine = 0;
  for (const line of lines) {
    const range = HUNK_RANGE.exec(line);
    if (range) {
      const start = Number(range[1]);
      const count = range[2] === undefined ? 1 : Number(range[2]);
      maxLine = Math.max(maxLine, start + count);
    }
  }
  const width = Math.max(String(maxLine).length, 3);
  const blank = " ".repeat(width);

  let newLine = 0;
  let inHunk = false;
  const out: string[] = [];
  for (const line of lines) {
    if (line.startsWith("diff --git")) {
      inHunk = false;
      out.push(`${blank}  ${line}`);
      continue;
    }
    const range = HUNK_RANGE.exec(line);
    if (range) {
      inHunk = true;
      newLine = Number(range[1]);
      out.push(`${blank}  ${line}`);
      continue;
    }
    // Outside a hunk body (file headers, `index`, `---`/`+++`): no line number.
    if (!inHunk) {
      out.push(`${blank}  ${line}`);
      continue;
    }
    const marker = line[0];
    if (marker === "+" || marker === " ") {
      out.push(`${String(newLine).padStart(width)}  ${line}`);
      newLine++;
    } else {
      // Removed (`-`) lines and the `\ No newline at end of file` marker.
      out.push(`${blank}  ${line}`);
    }
  }
  return out.join("\n");
}

export type { DiffFile };
export {
  CHARS_PER_TOKEN_ESTIMATE,
  EXCLUDED_PATH_PATTERNS,
  annotateDiffWithLineNumbers,
  chunkDiffFiles,
  estimateTokens,
  partitionExcluded,
  splitDiffByFile,
};
