import { execFile } from "node:child_process";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

const MAX_BUFFER = 32 * 1024 * 1024; // 32MB — diffs can be large.

interface GitContext {
  /** Working directory the git commands run in. Defaults to process.cwd(). */
  cwd?: string;
}

/**
 * Run a git subcommand with explicit, array-form arguments (no shell), so
 * caller-supplied values can never be interpreted as shell metacharacters.
 */
async function runGit(args: readonly string[], ctx: GitContext = {}): Promise<string> {
  const { stdout } = await execFileAsync("git", [...args], {
    cwd: ctx.cwd ?? process.cwd(),
    maxBuffer: MAX_BUFFER,
  });
  return stdout.trimEnd();
}

async function currentBranch(ctx?: GitContext): Promise<string> {
  return runGit(["rev-parse", "--abbrev-ref", "HEAD"], ctx);
}

/**
 * Git pathspecs excluded from {@link diff} by default. These cover machine-
 * generated dependency lockfiles and committed Yarn Plug'n'Play / zero-install
 * artifacts — content that is regenerated by tooling, not authored, and not
 * meaningful to review line-by-line. They are also enormous and token-dense:
 * excluding them at the git level keeps the diff from overflowing a model's
 * context window. The downstream code-reviewer applies the same exclusions as
 * defense-in-depth.
 *
 * Filename patterns use glob exclude pathspecs (a leading double-star) so they
 * match at any depth; the `.yarn` directory artifacts are repo-root-anchored
 * prefix matches.
 */
const DEFAULT_DIFF_EXCLUDES: readonly string[] = [
  // Dependency lockfiles.
  ":(exclude,glob)**/yarn.lock",
  ":(exclude,glob)**/package-lock.json",
  ":(exclude,glob)**/npm-shrinkwrap.json",
  ":(exclude,glob)**/pnpm-lock.yaml",
  ":(exclude,glob)**/composer.lock",
  ":(exclude,glob)**/Gemfile.lock",
  ":(exclude,glob)**/Cargo.lock",
  ":(exclude,glob)**/poetry.lock",
  ":(exclude,glob)**/Pipfile.lock",
  ":(exclude,glob)**/go.sum",
  ":(exclude,glob)**/mix.lock",
  ":(exclude,glob)**/flake.lock",
  ":(exclude,glob)**/Podfile.lock",
  ":(exclude,glob)**/packages.lock.json",
  ":(exclude,glob)**/pubspec.lock",
  // Yarn Plug'n'Play / zero-install artifacts.
  ":(exclude,glob)**/.pnp.cjs",
  ":(exclude,glob)**/.pnp.loader.mjs",
  ":(exclude,glob)**/.pnp.data.json",
  ":(exclude).yarn/cache",
  ":(exclude).yarn/unplugged",
  ":(exclude).yarn/install-state.gz",
];

interface DiffOptions {
  /** Base ref, e.g. 'origin/main'. */
  base?: string;
  /** Head ref, e.g. the PR branch or 'HEAD'. */
  head?: string;
  /** Restrict the diff to these paths. */
  paths?: readonly string[];
  /**
   * Include machine-generated lockfiles and Yarn PnP/zero-install artifacts
   * that are excluded by default (see {@link DEFAULT_DIFF_EXCLUDES}).
   */
  includeGenerated?: boolean;
}

/**
 * Produce a unified diff. With `base` and `head`, diffs the symmetric range
 * `base...head` (changes on head since it diverged from base). With only
 * `base`, diffs the working tree against base. Machine-generated lockfiles and
 * Yarn PnP/zero-install artifacts are excluded unless `includeGenerated` is set.
 */
async function diff(options: DiffOptions = {}, ctx?: GitContext): Promise<string> {
  const { base, head, paths, includeGenerated } = options;
  const args = ["diff"];
  if (base && head) {
    args.push(`${base}...${head}`);
  } else if (base) {
    args.push(base);
  }

  // Assemble the pathspec list: any caller-supplied positive paths, plus the
  // default exclusions unless explicitly disabled. Git rejects an exclude-only
  // pathspec list, so a positive pathspec (`.`) is added when the caller gave
  // none.
  const pathspecs: string[] = paths?.length ? [...paths] : [];
  if (!includeGenerated) {
    if (!pathspecs.length) pathspecs.push(".");
    pathspecs.push(...DEFAULT_DIFF_EXCLUDES);
  }
  if (pathspecs.length) {
    args.push("--", ...pathspecs);
  }
  return runGit(args, ctx);
}

/** Return the fetch URL of a remote (defaults to `origin`). */
async function remoteUrl(remote = "origin", ctx?: GitContext): Promise<string> {
  return runGit(["remote", "get-url", remote], ctx);
}

async function mergeBase(ref: string, base: string, ctx?: GitContext): Promise<string> {
  return runGit(["merge-base", base, ref], ctx);
}

/** Fetch the given refs from a remote (defaults to `origin`) so remote-tracking refs are current. */
async function fetchRefs(
  refs: readonly string[],
  remote = "origin",
  ctx?: GitContext,
): Promise<void> {
  if (!refs.length) return;
  await runGit(["fetch", remote, ...refs], ctx);
}

/**
 * Count commits reachable from `ref` but not from `base` — how far `ref` is
 * ahead of `base`. Returns `null` when the comparison can't be made, e.g.
 * `base` doesn't exist (a branch that has never been pushed to the remote).
 */
async function aheadCount(ref: string, base: string, ctx?: GitContext): Promise<number | null> {
  try {
    const out = await runGit(["rev-list", "--count", `${base}..${ref}`], ctx);
    return parseInt(out, 10) || 0;
  } catch {
    return null;
  }
}

/**
 * Detect the repository's default branch.
 *
 * Prefers the remote's advertised default (`origin/HEAD`); falls back to a
 * local `main`/`master` if it exists, then to `"main"`.
 */
async function defaultBranch(ctx?: GitContext): Promise<string> {
  try {
    const ref = await runGit(["symbolic-ref", "--short", "refs/remotes/origin/HEAD"], ctx);
    return ref.replace(/^origin\//, "");
  } catch {
    for (const candidate of ["main", "master"]) {
      try {
        await runGit(["rev-parse", "--verify", "--quiet", candidate], ctx);
        return candidate;
      } catch {
        // try next candidate
      }
    }
    return "main";
  }
}

export type { DiffOptions, GitContext };
export {
  DEFAULT_DIFF_EXCLUDES,
  aheadCount,
  currentBranch,
  defaultBranch,
  diff,
  fetchRefs,
  mergeBase,
  remoteUrl,
  runGit,
};
